version: "3.8"

x-AWS_ACCESS_KEY_ID: &aws-access-key-id ${AWS_ACCESS_KEY_ID:-aws_key_id}
x-AWS_SECRET_ACCESS_KEY: &aws-secret-access-key ${AWS_SECRET_ACCESS_KEY:-aws_secret_key}
x-AWS_DEFAULT_REGION: &aws-default-region ${AWS_DEFAULT_REGION:-eu-west-1}

services:
  s3:
    image: minio/minio
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: *aws-access-key-id
      MINIO_ROOT_PASSWORD: *aws-secret-access-key
      MINIO_REGION_NAME: *aws-default-region
      # MINIO_USERNAME: minioadmin
      # MINIO_GROUPNAME: minioadmin
      # MINIO_UID: 1000
      # MINIO_GID: 1000
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:9000/minio/health/live"
        ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - ./docker/s3/data/:/data
