name: food-pricing
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - nodejs
  - pip

  - pip:
    - -e .

  - ipython
  - ipykernel
  - jupyterlab
  
  - dask
  - dask-labextension
  - s3fs
  - pyarrow
  - pandas
  - numpy
  - scipy
  - seaborn
  - scikit-learn
  - scikit-optimize
  - pytorch
  - pytorch-lightning
  - torchvision
  - fasttext
  - xgboost
  - black
  - jupyterlab_code_formatter
  - flake8
  - python-dotenv
  - pydantic
  - lxml
  - bokeh
  - python-graphviz
  - ipywidgets
  - geopy
  - tensorboard
  - captum
  - flask
  - transformers
  - knockknock
